# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}
    
    def teardown_method(self, method):
        self.driver.quit()
    
    def test_01FlowPurchaseTest(self):
        self.driver.get("https://www.demoblaze.com/")
        self.driver.set_window_size(826, 816)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.ID, "narvbarx"))).click()
    
    def test_02Navigatetoproductcategory(self):
        self.driver.get("https://www.demoblaze.com/")
        self.driver.set_window_size(826, 816)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.ID, "itemc"))).click()
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.LINK_TEXT, "Laptops"))).click()
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.LINK_TEXT, "Monitors"))).click()
    
    def test_03Selectaproduct(self):
        self.driver.get("https://www.demoblaze.com/")
        self.driver.set_window_size(826, 816)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".col-lg-4:nth-child(1) .card-img-top"))).click()
    
    def test_04Addtocart(self):
        self.driver.get("https://www.demoblaze.com/")
        self.driver.set_window_size(830, 816)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".col-lg-4:nth-child(1) .card-img-top"))).click()
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.LINK_TEXT, "Add to cart"))).click()
        
        # Manejar la alerta
        alert = WebDriverWait(self.driver, 10).until(EC.alert_is_present())
        assert alert.text == "Product added"
        alert.accept()
    
    def test_05Gotocart(self):
        self.driver.get("https://www.demoblaze.com/")
        self.driver.set_window_size(1552, 832)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.ID, "cartur"))).click()
    
    def test_06Purchaseprocedure(self):
        self.driver.get("https://www.demoblaze.com/")
        self.driver.set_window_size(1552, 832)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.ID, "cartur"))).click()
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".btn-success"))).click()
        
        # Eliminar los parámetros adicionales en move_to_element
        element = WebDriverWait(self.driver, 10).until(EC.visibility_of_element_located((By.CSS_SELECTOR, ".btn-success")))
        actions = ActionChains(self.driver)
        actions.move_to_element(element).perform()
    
    def test_07Completetheshippinginformation(self):
        self.driver.get("https://www.demoblaze.com/")
        self.driver.set_window_size(1552, 832)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.ID, "cartur"))).click()
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".btn-success"))).click()
        
        # Completar el formulario de envío
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.ID, "name"))).send_keys("Adán Israel Pérez Cruz")
        self.driver.find_element(By.ID, "country").send_keys("México")
        self.driver.find_element(By.ID, "city").send_keys("Tula de Allende")
        self.driver.find_element(By.ID, "card").send_keys("3710374628012848")
        self.driver.find_element(By.ID, "month").send_keys("14000")
        self.driver.find_element(By.ID, "year").send_keys("2005")
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, "#orderModal .btn-primary"))).click()
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".confirm"))).click()
    
    def test_08Simulatepayment(self):
        self.driver.get("https://www.demoblaze.com/")
        self.driver.set_window_size(1552, 832)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.ID, "cartur"))).click()
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".btn-success"))).click()
        
        # Completar los detalles de pago
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.ID, "name"))).send_keys("Adán Israel Pérez Cruz")
        self.driver.find_element(By.ID, "country").send_keys("México")
        self.driver.find_element(By.ID, "city").send_keys("Tula de Allende")
        self.driver.find_element(By.ID, "card").send_keys("431241242134214321")
        self.driver.find_element(By.ID, "month").send_keys("14000")
        self.driver.find_element(By.ID, "year").send_keys("4312")
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, "#orderModal .btn-primary"))).click()
    
    def test_09Checkconfirmation(self):
        self.driver.get("https://www.demoblaze.com/")
        self.driver.set_window_size(1552, 832)
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.ID, "cartur"))).click()
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".btn-success"))).click()
        
        # Completar los detalles de confirmación
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.ID, "name"))).send_keys("Adán Israel Pérez Cruz")
        self.driver.find_element(By.ID, "country").send_keys("México")
        self.driver.find_element(By.ID, "city").send_keys("Tula de Allende")
        self.driver.find_element(By.ID, "card").send_keys("32141341413124321")
        self.driver.find_element(By.ID, "month").send_keys("09")
        self.driver.find_element(By.ID, "year").send_keys("2005")
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, "#orderModal .btn-primary"))).click()
        WebDriverWait(self.driver, 10).until(EC.element_to_be_clickable((By.CSS_SELECTOR, ".confirm"))).click()
